package controllers;

import javafx.fxml.FXML;
import javafx.stage.Stage;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class MainSceneController {
	@FXML
	private TextField tfTitle;

	// Event Listener on Button.onAction
	@FXML
	public void btnOKClicked(ActionEvent event) {
		// TODO Autogenerated
		Stage mainWindow = (Stage) tfTitle.getScene().getWindow();
		String title = tfTitle.getText();
		mainWindow.setTitle(title);
	}
}
